import {
  JUNO_WEBHOOK_EVENT_DIGITAL_ACCOUNT_STATUS_CHANGED, JUNO_WEBHOOK_EVENT_DIGITAL_ACCOUNT_CREATED, JUNO_WEBHOOK_EVENT_DOCUMENT_STATUS_CHANGED, JUNO_WEBHOOK_EVENT_TRANSFER_STATUS_CHANGED, JUNO_WEBHOOK_EVENT_P2P_TRANSFER_STATUS_CHANGED, JUNO_WEBHOOK_EVENT_CHARGE_STATUS_CHANGED, JUNO_WEBHOOK_EVENT_CHARGE_READ_CONFIRMATION, JUNO_WEBHOOK_EVENT_PAYMENT_NOTIFICATION,
} from './../../juno.constants';
import { JunoWebhookMethodDecorator } from './juno.webhook.method.decorator';

export const JunoWebhookEventDigitalAccountStatusChanged = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_DIGITAL_ACCOUNT_STATUS_CHANGED);
export const JunoWebhookEventDigitalAccountCreated = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_DIGITAL_ACCOUNT_CREATED);
export const JunoWebhookEventDocumentStatusChanged = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_DOCUMENT_STATUS_CHANGED);
export const JunoWebhookEventTransferStatusChanged = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_TRANSFER_STATUS_CHANGED);
export const JunoWebhookEventP2PTransferStatusChanged = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_P2P_TRANSFER_STATUS_CHANGED);
export const JunoWebhookEventChargeStatusChanged = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_CHARGE_STATUS_CHANGED);
export const JunoWebhookEventChargeReadConfirmation = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_CHARGE_READ_CONFIRMATION);
export const JunoWebhookEventPaymentNotification = JunoWebhookMethodDecorator(JUNO_WEBHOOK_EVENT_PAYMENT_NOTIFICATION);