export const JUNO_OPTIONS_PROVIDER = 'JUNO_OPTIONS_PROVIDER';
export const JUNO_WEBHOOK_METHOD = 'JUNO_WEBHOOK_METHOD';
export const JUNO_WEBHOOK_PROVIDER = 'JUNO_WEBHOOK_PROVIDER';
export const JUNO_AUTHORIZATION_TOKEN = 'JUNO_AUTHORIZATION_TOKEN';

// new

export const JUNO_WEBHOOK_EVENT_DIGITAL_ACCOUNT_STATUS_CHANGED = 'DIGITAL_ACCOUNT_STATUS_CHANGED';
export const JUNO_WEBHOOK_EVENT_DIGITAL_ACCOUNT_CREATED = 'DIGITAL_ACCOUNT_CREATED';
export const JUNO_WEBHOOK_EVENT_DOCUMENT_STATUS_CHANGED = 'DOCUMENT_STATUS_CHANGED';
export const JUNO_WEBHOOK_EVENT_TRANSFER_STATUS_CHANGED = 'TRANSFER_STATUS_CHANGED';
export const JUNO_WEBHOOK_EVENT_P2P_TRANSFER_STATUS_CHANGED = 'P2P_TRANSFER_STATUS_CHANGED';
export const JUNO_WEBHOOK_EVENT_CHARGE_STATUS_CHANGED = 'CHARGE_STATUS_CHANGED';
export const JUNO_WEBHOOK_EVENT_CHARGE_READ_CONFIRMATION = 'CHARGE_READ_CONFIRMATION';
export const JUNO_WEBHOOK_EVENT_PAYMENT_NOTIFICATION = 'PAYMENT_NOTIFICATION';

// Requests
export const JUNO_WEBHOOK_AUTHORIZATION_SERVER_POST = 'authorization-server/oauth/token';